name: Update LeetCode Stats

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs on sunday at midnight
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README with LeetCode stats
        run: |
          echo "![LeetCode Stats](https://leetcode-stats.vercel.app/api?username=Tiago_Bittencourt&theme=dark)" >> README.md
          git config --local user.email "tiago.bittencourt.2005@gmail.com"
          git config --local user.name "Tiago_Bittenocurt"
          git add README.md
          git commit -m "Update LeetCode stats" || echo "No changes to commit"
          git push
